version: '2'

services:
  zookeeper:
    image: "wurstmeister/zookeeper"
    ports:
      - "2181:2181"

  kafka:
    image: "wurstmeister/kafka"
    ports:
      - "9092:9092"
    depends_on:
      - "zookeeper"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"


  couchbase:
    build: ./couchbase
    ports:
      - 8091-8093:8091-8093
      - 11210:11210



  spring-boot:
    build:  .
    ports:
      - 8082:8082
    depends_on:
      - "kafka"
      - "couchbase"
    restart: always